import igOverlay from '../assets/img/instagram-overlay.png';
import igOverlayXL from '../assets/img/instagram-overlay-xl.png';
import igWidget from './igWidget.js';
import twitterWidget from './twitterWidget.js';
import copyContact from './copyContact.js';
import sideMenu from './sideMenu.js';
import gradNavbar from './gradNavbar.js';
import playPauseBtn from './playPauseBtn.js';
import indexCSS from '../styles/index.css';